openapi: 3.0.1
info:
  title: Swagger Example API
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  contact: {}
  version: "1.0"
servers:
- url: //localhost:8080/
paths:
  /admin:
    post:
      tags:
      - admin
      summary: Ingresar datos especificos
      description: Updates a value associated with a user after Basic Auth validation
      requestBody:
        description: Input Json con algun valor
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          description: "status: ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.SuccessResponse'
        "400":
          description: "error: invalid request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.ErrorResponse'
        "401":
          description: "error: unauthorized"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.ErrorResponse'
      security:
      - BasicAuth: []
      x-codegen-request-body-name: body
  /someJSON:
    get:
      summary: Show a JSON response
      description: Returns a simple JSON object
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /testing:
    post:
      tags:
      - default
      summary: Process form data and display result
      description: Accepts form data and returns the formatted response as a string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - address
              - birthday
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Name of the person
                address:
                  type: string
                  description: Address of the person
                birthday:
                  type: string
                  description: Birthday of the person (YYYY-MM-DD)
        required: true
      responses:
        "200":
          description: "Formatted response with name, address, and birthday"
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Invalid form data
          content:
            text/plain:
              schema:
                type: object
                additionalProperties: true
components:
  schemas:
    main.ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: invalid request
    main.SuccessResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
x-original-swagger-version: "2.0"